In [1]:
import numpy as np

In [3]:
arr = np.array([[1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]])

In [16]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])

In [17]:
arr2.shape

(7,)

In [19]:
arr2[[1, 6, 4]]

array([2, 7, 5])

In [26]:
roll = [1, 2, 3, 4, 5]
name = ["jatin", "chirag", "harshita", "ibrahim"]

In [27]:
# for i in range(len(roll)):
for r, n in zip(roll, name):
    print(r, n)

1 jatin
2 chirag
3 harshita
4 ibrahim


In [32]:
r = [0, 1, 2]
c = [2, 1, 0]
for i, j in zip(r, c):
    print(arr[i][j])
print(arr[r, c])

3
5
7
[3 5 7]


In [14]:
print(arr[0][1])
print(arr[0, 1])

2
2


In [15]:
for x in arr[:2]:
    print(x[:1])
print(arr[:2, :1])

[1]
[4]
[[1]
 [4]]


In [5]:
arr[[0, 1, 2], [0, 1, 2]]

array([1, 5, 9])

In [7]:
arr[[0, 1, 2], [2, 1, 0]]

array([3, 5, 7])

In [ ]:
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if i == j:
            pass
        elif i+j == 2:
            pass

In [34]:
np.diag?

In [54]:
b = np.diag(np.fliplr(arr))

In [55]:
a = np.diag(arr)

In [56]:
np.array(list(zip(a, b)))

array([[1, 3],
       [5, 5],
       [9, 7]])

```py
[[1, 3],
[5, 5],
[9, 7]]
```

In [ ]:
[("jatin", 1, 1.6), ("jatin", 1, 1.6)]
2,
2, 3
np.array()